import { fn } from 'storybook/test';

// Mock the useCoins hook
export const useCoins = fn()
  .mockName('useCoins')
  .mockReturnValue({
    handleStorageData: async () => Promise.resolve(),
    updateTokenFilter: () => {},
    coins: [
      {
        address: 'A.1654653399040a61.FlowToken',
        name: 'Flow Token',
        contractName: 'FlowToken',
        decimals: 8,
        symbol: 'FLOW',
        path: {
          vault: '/storage/flowTokenVault',
          receiver: '/public/flowTokenReceiver',
          balance: '/storage/flowTokenBalance',
        },
        logoURI: 'https://example.com/flow-logo.png',
        tags: ['verified'],
        id: 'A.1654653399040a61.FlowToken',
        coin: 'flow',
        unit: 'flow',
        balance: '100.5',
        price: '1.5',
        change24h: 0.05,
        total: '150.75',
        icon: 'https://example.com/flow-logo.png',
        priceInUSD: '1.5',
        balanceInUSD: '150.75',
        priceInFLOW: '1.0',
        balanceInFLOW: '100.5',
      },
      {
        address: 'A.1654653399040a61.USDC',
        name: 'USD Coin',
        contractName: 'USDC',
        decimals: 6,
        symbol: 'USDC',
        path: {
          vault: '/storage/usdcVault',
          receiver: '/public/usdcReceiver',
          balance: '/storage/usdcBalance',
        },
        logoURI: 'https://example.com/usdc-logo.png',
        tags: ['verified'],
        id: 'A.1654653399040a61.USDC',
        coin: 'usdc',
        unit: 'usdc',
        balance: '500.0',
        price: '1.0',
        change24h: 0.0,
        total: '500.0',
        icon: 'https://example.com/usdc-logo.png',
        priceInUSD: '1.0',
        balanceInUSD: '500.0',
        priceInFLOW: '1.0',
        balanceInFLOW: '500.0',
      },
      {
        address: 'A.1654653399040a61.WETH',
        name: 'Wrapped Ethereum',
        contractName: 'WETH',
        decimals: 18,
        symbol: 'WETH',
        path: {
          vault: '/storage/wethVault',
          receiver: '/public/wethReceiver',
          balance: '/storage/wethBalance',
        },
        logoURI: 'https://example.com/weth-logo.png',
        tags: ['verified'],
        id: 'A.1654653399040a61.WETH',
        coin: 'weth',
        unit: 'weth',
        balance: '2.5',
        price: '2000.0',
        change24h: 0.02,
        total: '5000.0',
        icon: 'https://example.com/weth-logo.png',
        priceInUSD: '2000.0',
        balanceInUSD: '5000.0',
        priceInFLOW: '2000.0',
        balanceInFLOW: '2.5',
      },
    ],
    tokenFilter: {
      hideDust: false,
      hideUnverified: true,
      filteredIds: [],
    },
    balance: '0',
    totalFlow: '0',
    availableFlow: '0',
    coinsLoaded: true,
  });
